import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { Inter as FontSans } from "next/font/google";
// import { cn } from "@/lib/utils";
import "./globals.css";
import { SetContextProvider } from "@/contexts/setContext";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster";
// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={cn(
        //   "min-h-screen bg-background font-sans antialiased",
        //   fontSans.variable
        // )}

        className={inter.className}
      >
        <SetContextProvider>
          {children}
          <Toaster />
        </SetContextProvider>
      </body>
    </html>
  );
}
